import "./globals.css";
import Link from "next/link";
import LoginBtn from "@/app/loginBtn";
import {getServerSession} from "next-auth";
import {authOptions} from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "@/app/logoutBtn";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    let session = await getServerSession(authOptions)
    console.log(session)

  return (
    <html lang="en">
      <body>
      <div className="navbar">
        <Link href="/" className="logo">
          home
        </Link>
        <Link href="/list">List</Link>
        <Link href="/write">Write</Link>
          {session ? <span>{session.user.name} <LogoutBtn /> </span> : <LoginBtn />}
      </div>
        {children}</body>
    </html>
  );
}
